### PR TITLE
added "reserved_concurrent_executions" parameter

### PR DESCRIPTION
**Pull request by TomasMocek**

### CODE REVIEW

**Review by mikael-lindstrom — COMMENTED** [review]
LGTM but before we merge we should add a line to the readme stating that it requires the AWS provider >= 2.0.0.

**Comment by TomasMocek** [comment]
@mikael-lindstrom It does not necessarily requires provider 2.0.0. It just will not be in sync with the documentation for previous versions.
Before 2.0.0: values -1 and 0 should both mean the same: unreserved concurrency
After 2.0.0:    -1 means unreserved and 0 means that the lambda is disabled

**Comment by mikael-lindstrom** [comment]
My misunderstanding, I though it would not work with < 2.0.0 since -1 was not supported but looking at the provider code it should work just fine. I can merge and tag a new release for this.

**Review by mikael-lindstrom — APPROVED** [review]
LGTM 👍

**Pull request merged**
